package org.mum.scrum.entities;
// Generated Apr 7, 2016 10:07:25 PM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name = "projects", catalog = "mumscrum_prod")
public class Projects implements java.io.Serializable {

	private Integer id;
	private Users users;
	private String name;
	private String description;
	private Boolean status;
	private Set<Sprints> sprintses = new HashSet<Sprints>(0);

	public Projects() {
	}

	public Projects(Users users, String name, String description, Boolean status, Set<Sprints> sprintses) {
		this.users = users;
		this.name = name;
		this.description = description;
		this.status = status;
		this.sprintses = sprintses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<Sprints> getSprintses() {
		return this.sprintses;
	}

	public void setSprintses(Set<Sprints> sprintses) {
		this.sprintses = sprintses;
	}

}
