package org.mum.scrum.entities;
// Generated Apr 9, 2016 12:05:30 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Userstory generated by hbm2java
 */
@Entity
@Table(name = "userstory", catalog = "mumscrum_prod")
public class Userstory implements java.io.Serializable {

	private Integer id;
	private Sprint sprint;
	private User user;
	private String name;
	private String description;
	private Integer estimatedTime;
	private Boolean status;
	private Project project;
	private Set<Timelog> timelogs = new HashSet<Timelog>(0);
	private Integer completedTime;

	public Userstory() {
	}

	public Userstory(String name) {
		this.name = name;
	}

	public Userstory(Sprint sprint, User user, String name, String description, Integer estimatedTime, Boolean status,
			Set<Timelog> timelogs) {
		this.sprint = sprint;
		this.user = user;
		this.name = name;
		this.description = description;
		this.estimatedTime = estimatedTime;
		this.status = status;
		this.timelogs = timelogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sprint_id")
	public Sprint getSprint() {
		return this.sprint;
	}

	public void setSprint(Sprint sprint) {
		this.sprint = sprint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "estimatedTime")
	public Integer getEstimatedTime() {
		return this.estimatedTime;
	}

	public void setEstimatedTime(Integer estimatedTime) {
		this.estimatedTime = estimatedTime;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userstory")
	public Set<Timelog> getTimelogs() {
		return this.timelogs;
	}

	public void setTimelogs(Set<Timelog> timelogs) {
		this.timelogs = timelogs;
	}
	
	@Column(name = "completedTime")
	public Integer getCompletedTime() {
		return this.completedTime;
	}

	public void setCompletedTime(Integer completedTime) {
		this.completedTime = completedTime;
	}
}
