package org.mum.scrum.entities;
// Generated Apr 7, 2016 10:07:25 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userstory generated by hbm2java
 */
@Entity
@Table(name = "userstory", catalog = "mumscrum_prod")
public class Userstory implements java.io.Serializable {

	private Integer id;
	private Sprints sprints;
	private String name;
	private String description;
	private Integer estimatedTime;
	private Boolean status;
	private Date assignedDate;
	private Set<Timelogs> timelogses = new HashSet<Timelogs>(0);

	public Userstory() {
	}

	public Userstory(Sprints sprints, String name, String description, Integer estimatedTime, Boolean status,
			Date assignedDate, Set<Timelogs> timelogses) {
		this.sprints = sprints;
		this.name = name;
		this.description = description;
		this.estimatedTime = estimatedTime;
		this.status = status;
		this.assignedDate = assignedDate;
		this.timelogses = timelogses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sprint_id")
	public Sprints getSprints() {
		return this.sprints;
	}

	public void setSprints(Sprints sprints) {
		this.sprints = sprints;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "estimatedTime")
	public Integer getEstimatedTime() {
		return this.estimatedTime;
	}

	public void setEstimatedTime(Integer estimatedTime) {
		this.estimatedTime = estimatedTime;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "assignedDate", length = 10)
	public Date getAssignedDate() {
		return this.assignedDate;
	}

	public void setAssignedDate(Date assignedDate) {
		this.assignedDate = assignedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userstory")
	public Set<Timelogs> getTimelogses() {
		return this.timelogses;
	}

	public void setTimelogses(Set<Timelogs> timelogses) {
		this.timelogses = timelogses;
	}

}
